/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.miraiseikou.core.view;

import com.miraiseikou.util.PropertiesManager;
import java.awt.Toolkit;
import java.net.URL;

/**
 *
 * @author jvlima
 */
public class SettingsView extends javax.swing.JFrame {
    PropertiesManager manager = new PropertiesManager();
    /**
     * Creates new form SettingsView
     */
    public SettingsView() {
        initComponents();
        init();
    }
    
    private void init() {
        setLocationRelativeTo(null);
        this.getRootPane().setDefaultButton(btnSave);
        URL resources = this.getClass().getResource("/images/logo.png");
        this.setIconImage(Toolkit.getDefaultToolkit().createImage(resources));
        txtToken.setText(manager.getProperty("token"));
        spnTolarance.setValue(Integer.valueOf(manager.getProperty("tolerance")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtToken = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblToken = new javax.swing.JLabel();
        lblTolerance = new javax.swing.JLabel();
        spnTolarance = new javax.swing.JSpinner();
        spnTimeUnity = new javax.swing.JLabel();

        setTitle("Configurações");
        setLocationByPlatform(true);
        setResizable(false);

        btnSave.setText("Salvar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblToken.setText("Slack Token:");

        lblTolerance.setText("Tempo de Tolerancia: ");

        spnTimeUnity.setText("Minutos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblToken)
                            .addComponent(lblTolerance))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spnTolarance, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnTimeUnity)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtToken, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSave)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblToken)
                    .addComponent(txtToken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTolerance)
                    .addComponent(spnTolarance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnTimeUnity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        manager.setProperty("token", txtToken.getText());
        manager.setProperty("tolerance", spnTolarance.getValue().toString());
    }//GEN-LAST:event_btnSaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblToken;
    private javax.swing.JLabel lblTolerance;
    private javax.swing.JLabel spnTimeUnity;
    private javax.swing.JSpinner spnTolarance;
    private javax.swing.JTextField txtToken;
    // End of variables declaration//GEN-END:variables
}
